project:
  type: website
  output-dir: docs
  resources:
    - files/resume.pdf

website:
  title: "Ethan Mathews"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about me.qmd
      - projects.qmd
      - past adventures.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

