project:
  type: website
  output-dir: docs
  resources:
    - files/resume.pdf
    - websitematerial/**

website:
  title: "Ethan Mathews"
  site-url: https://ethan-mathews24.github.io/ethan-mathews24/
  navbar:
    right:
      - href: index.qmd
        text: home
      - text: about me
        menu:
          - text: pets
            href: pets.qmd
          - text: hobbies
            href: hobbies.qmd
          - text: true passion
            href: true-passion.qmd
      - href: projects.qmd
        text: projects
      - href: past-adventures.qmd
        text: past adventures

filters:
  - lightbox

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

