project:
  type: website
  output-dir: docs
  resources:
    - files/resume.pdf

website:
  title: "Ethan Mathews"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

